import type { Question } from "@/lib/types";

export const SAMPLE_QUESTIONS: Question[] = [
  // ============================================================
  // FUNDAMENTALS (12 questions)
  // ============================================================
  {
    id: "fund-001",
    topic: "fundamentals",
    subtopic: "measurement",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Every measurement consists of two parts. What are they?",
      answer_type: "multiple-choice",
      correct_answer: "A number and a unit",
      choices: ["A number and a unit", "A number only", "A unit and an uncertainty", "A number, a unit, and a symbol"],
      explanation: "Every measurement = a number (magnitude) + a unit (what is being measured). For example, 25 mL has the number 25 and the unit mL.",
    },
  },
  {
    id: "fund-002",
    topic: "fundamentals",
    subtopic: "accuracy-vs-precision",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Four students measure the mass of a 10.00 g standard. Their results: 10.01, 10.02, 9.99, 10.00. These measurements are best described as:",
      answer_type: "multiple-choice",
      correct_answer: "Both accurate and precise",
      choices: ["Accurate but not precise", "Precise but not accurate", "Both accurate and precise", "Neither accurate nor precise"],
      explanation: "The values are close to the true value (10.00 g) → accurate. They are also close to each other (small spread) → precise.",
    },
  },
  {
    id: "fund-003",
    topic: "fundamentals",
    subtopic: "accuracy-vs-precision",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A student consistently gets 7.32 g for a sample whose true mass is 8.50 g. This is an example of:",
      answer_type: "multiple-choice",
      correct_answer: "Precise but not accurate",
      choices: ["Accurate but not precise", "Precise but not accurate", "Both accurate and precise", "Neither accurate nor precise"],
      explanation: "Consistent results = precise. But far from the true value (8.50 g) = not accurate. This often indicates a systematic error (e.g., uncalibrated balance).",
    },
  },
  {
    id: "fund-004",
    topic: "fundamentals",
    subtopic: "physical-chemical-properties",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Which of the following is a chemical property?",
      answer_type: "multiple-choice",
      correct_answer: "Iron rusts in moist air",
      choices: ["Iron rusts in moist air", "Iron has a density of 7.87 g/cm³", "Iron melts at 1538°C", "Iron is a gray metal"],
      explanation: "Rusting is a chemical change (new substance formed). Density, melting point, and color are physical properties — they describe the substance without changing its identity.",
    },
  },
  {
    id: "fund-005",
    topic: "fundamentals",
    subtopic: "physical-chemical-properties",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which process involves a chemical change?",
      answer_type: "multiple-choice",
      correct_answer: "Burning natural gas on a stove",
      choices: ["Boiling water to make steam", "Burning natural gas on a stove", "Dissolving salt in water", "Crushing a rock into powder"],
      explanation: "Burning natural gas (CH₄ + O₂ → CO₂ + H₂O) produces new substances — a chemical change. The others are physical changes: state change, dissolving, and size reduction.",
    },
  },
  {
    id: "fund-006",
    topic: "fundamentals",
    subtopic: "states-of-matter",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Which state of matter has a definite volume but takes the shape of its container?",
      answer_type: "multiple-choice",
      correct_answer: "Liquid",
      choices: ["Solid", "Liquid", "Gas", "Plasma"],
      explanation: "Solids: definite shape + volume. Liquids: indefinite shape + definite volume. Gases: indefinite shape + indefinite volume.",
    },
  },
  {
    id: "fund-007",
    topic: "fundamentals",
    subtopic: "atoms-molecules",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the relationship between atoms and molecules?",
      answer_type: "multiple-choice",
      correct_answer: "A molecule is two or more atoms bonded together",
      choices: ["A molecule is two or more atoms bonded together", "An atom is made of molecules", "Atoms and molecules are identical", "A molecule is a single atom"],
      explanation: "An atom is the smallest unit of an element. A molecule is two or more atoms chemically bonded (e.g., H₂O = 2 H atoms + 1 O atom).",
    },
  },
  {
    id: "fund-008",
    topic: "fundamentals",
    subtopic: "elements-compounds",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which of the following is a compound?",
      answer_type: "multiple-choice",
      correct_answer: "Carbon dioxide (CO₂)",
      choices: ["Carbon dioxide (CO₂)", "Oxygen (O₂)", "Iron (Fe)", "Helium (He)"],
      explanation: "A compound contains two or more different elements chemically combined. CO₂ has carbon AND oxygen. O₂, Fe, and He are elements (single type of atom).",
    },
  },
  {
    id: "fund-009",
    topic: "fundamentals",
    subtopic: "mixtures",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A mixture of salt dissolved in water is best classified as:",
      answer_type: "multiple-choice",
      correct_answer: "A homogeneous mixture (solution)",
      choices: ["A homogeneous mixture (solution)", "A heterogeneous mixture", "A compound", "A pure element"],
      explanation: "Salt water is uniform throughout → homogeneous mixture (solution). The salt and water retain their individual properties and can be separated by physical means (evaporation).",
    },
  },
  {
    id: "fund-010",
    topic: "fundamentals",
    subtopic: "mass-vs-weight",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "An astronaut has a mass of 70 kg on Earth. What is their mass on the Moon?",
      answer_type: "multiple-choice",
      correct_answer: "70 kg",
      choices: ["70 kg", "About 11.7 kg", "About 420 kg", "Zero"],
      explanation: "Mass is the amount of matter — it does not change with location. Weight changes due to gravity (Moon gravity ≈ 1/6 of Earth's), but mass stays 70 kg.",
    },
  },
  {
    id: "fund-011",
    topic: "fundamentals",
    subtopic: "scientific-method",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A hypothesis is best defined as:",
      answer_type: "multiple-choice",
      correct_answer: "A testable explanation for an observation",
      choices: ["A testable explanation for an observation", "A proven fact about nature", "An educated guess that cannot be tested", "A law of nature"],
      explanation: "A hypothesis is a proposed, testable explanation. After repeated testing and verification, a hypothesis may become a theory. A law describes what happens (not why).",
    },
  },
  {
    id: "fund-012",
    topic: "fundamentals",
    subtopic: "density",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "An object has a mass of 27.0 g and a volume of 10.0 mL. What is its density?",
      answer_type: "numeric",
      correct_answer: 2.7,
      explanation: "Density = mass / volume = 27.0 g / 10.0 mL = 2.70 g/mL. This is the density of aluminum.",
    },
  },

  // ============================================================
  // METRIC SYSTEM (12 questions)
  // ============================================================
  {
    id: "metric-001",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'kilo' (k) mean?",
      answer_type: "multiple-choice",
      correct_answer: "1000",
      choices: ["100", "1000", "0.01", "0.001"],
      explanation: "kilo = 10³ = 1000. So 1 kg = 1000 g, 1 km = 1000 m.",
    },
  },
  {
    id: "metric-002",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'milli' (m) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.001",
      choices: ["0.1", "0.01", "0.001", "0.000001"],
      explanation: "milli = 10⁻³ = 0.001. So 1 mL = 0.001 L, 1 mg = 0.001 g.",
    },
  },
  {
    id: "metric-003",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'micro' (µ) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.000001",
      choices: ["0.001", "0.0001", "0.000001", "0.000000001"],
      explanation: "micro (µ) = 10⁻⁶ = 0.000001. So 1 µg = 0.000001 g.",
    },
  },
  {
    id: "metric-004",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'nano' (n) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.000000001",
      choices: ["0.000001", "0.0000001", "0.000000001", "0.0000000001"],
      explanation: "nano (n) = 10⁻⁹ = 0.000000001. Used in nanotechnology — structures on the scale of atoms and molecules.",
    },
  },
  {
    id: "metric-005",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'centi' (c) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.01",
      choices: ["0.1", "0.01", "100", "0.001"],
      explanation: "centi = 10⁻² = 0.01. So 1 cm = 0.01 m. There are 100 cm in 1 m.",
    },
  },
  {
    id: "metric-006",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'deci' (d) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.1",
      choices: ["0.1", "10", "0.01", "1"],
      explanation: "deci = 10⁻¹ = 0.1. So 1 dm = 0.1 m. There are 10 dm in 1 m.",
    },
  },
  {
    id: "metric-007",
    topic: "metric-system",
    subtopic: "base-units",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the SI base unit for mass?",
      answer_type: "multiple-choice",
      correct_answer: "Kilogram (kg)",
      choices: ["Gram (g)", "Kilogram (kg)", "Pound (lb)", "Milligram (mg)"],
      explanation: "The SI base unit for mass is the kilogram (kg), not the gram. The gram is a derived unit (1/1000 of a kg).",
    },
  },
  {
    id: "metric-008",
    topic: "metric-system",
    subtopic: "base-units",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the SI base unit for length?",
      answer_type: "multiple-choice",
      correct_answer: "Meter (m)",
      choices: ["Foot (ft)", "Meter (m)", "Centimeter (cm)", "Kilometer (km)"],
      explanation: "The SI base unit for length is the meter (m). All other length units (km, cm, mm, etc.) are derived from the meter using prefixes.",
    },
  },
  {
    id: "metric-009",
    topic: "metric-system",
    subtopic: "base-units",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the SI base unit for temperature?",
      answer_type: "multiple-choice",
      correct_answer: "Kelvin (K)",
      choices: ["Celsius (°C)", "Kelvin (K)", "Fahrenheit (°F)", "Joule (J)"],
      explanation: "The SI base unit for temperature is the Kelvin (K). Celsius is commonly used but is not the SI base unit. K = °C + 273.15.",
    },
  },
  {
    id: "metric-010",
    topic: "metric-system",
    subtopic: "prefix-conversion",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Convert 2.5 g to mg.",
      answer_type: "numeric",
      correct_answer: 2500,
      explanation: "1 g = 1000 mg. So 2.5 g × 1000 mg/g = 2500 mg.",
    },
  },
  {
    id: "metric-011",
    topic: "metric-system",
    subtopic: "prefix-conversion",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Convert 375 mg to g.",
      answer_type: "numeric",
      correct_answer: 0.375,
      explanation: "1 mg = 0.001 g. So 375 mg × 0.001 g/mg = 0.375 g.",
    },
  },
  {
    id: "metric-012",
    topic: "metric-system",
    subtopic: "prefix-conversion",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 0.0450 km to cm.",
      answer_type: "numeric",
      correct_answer: 4500,
      explanation: "0.0450 km → 45.0 m (×1000) → 4500 cm (×100). Two steps: km→m, then m→cm.",
    },
  },

  // ============================================================
  // SIGNIFICANT FIGURES (18 questions)
  // ============================================================
  {
    id: "sigfig-001",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 3.45?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "All non-zero digits are significant. 3, 4, and 5 → 3 sig figs.",
    },
  },
  {
    id: "sigfig-002",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 2006?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "Non-zero digits are significant, and captive zeros (between non-zero digits) are significant. 2, 0, 0, 6 → 4 sig figs.",
    },
  },
  {
    id: "sigfig-003",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.0042?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "Leading zeros are NOT significant — they just locate the decimal. Only 4 and 2 count → 2 sig figs.",
    },
  },
  {
    id: "sigfig-004",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 8370.00?",
      answer_type: "numeric",
      correct_answer: 6,
      explanation: "Non-zero digits (8,3,7), captive zero (0), and trailing zeros after the decimal (0,0) are all significant → 6 sig figs.",
    },
  },
  {
    id: "sigfig-005",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 100.0?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "The 1, the two captive zeros, and the trailing zero after the decimal are all significant → 4 sig figs.",
    },
  },
  {
    id: "sigfig-006",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 4.0200?",
      answer_type: "numeric",
      correct_answer: 5,
      explanation: "4, 0 (captive), 2, 0 (trailing), 0 (trailing) — all significant → 5 sig figs.",
    },
  },
  {
    id: "sigfig-007",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.0005?",
      answer_type: "numeric",
      correct_answer: 1,
      explanation: "Leading zeros never count. Only the 5 is significant → 1 sig fig.",
    },
  },
  {
    id: "sigfig-008",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 10.030?",
      answer_type: "numeric",
      correct_answer: 5,
      explanation: "1, 0 (captive), 0 (captive), 3, and 0 (trailing after decimal) → 5 sig figs.",
    },
  },
  {
    id: "sigfig-009",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 25.0?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "2, 5, and the trailing 0 after the decimal → 3 sig figs.",
    },
  },
  {
    id: "sigfig-010",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.03040?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "Leading zeros don't count. 3, 0 (captive), 4, and 0 (trailing after decimal) → 4 sig figs.",
    },
  },
  {
    id: "sigfig-011",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.0100?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "Leading zeros don't count. 1 and the two trailing zeros after the decimal → 3 sig figs.",
    },
  },
  {
    id: "sigfig-012",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 1.007?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "1, 0 (captive), 0 (captive), 7 → 4 sig figs.",
    },
  },
  {
    id: "sigfig-013",
    topic: "significant-figures",
    subtopic: "rounding-mult-div",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "For 2.5 × 2.5, how many significant figures should the answer have?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "For multiplication/division: the result has the same number of sig figs as the factor with the fewest. Both have 2 sig figs → answer should have 2.",
    },
  },
  {
    id: "sigfig-014",
    topic: "significant-figures",
    subtopic: "rounding-add-sub",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "For 12.1 + 3.447, how many decimal places should the answer have?",
      answer_type: "numeric",
      correct_answer: 1,
      explanation: "For addition/subtraction: the result has the same number of decimal places as the term with the fewest. 12.1 has 1 decimal place → answer should have 1.",
    },
  },
  {
    id: "sigfig-015",
    topic: "significant-figures",
    subtopic: "rounding-mult-div",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "For 4.56 × 1.4, how many significant figures should the answer have?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "1.4 has 2 sig figs (fewest), so the answer should have 2 sig figs. 4.56 × 1.4 = 6.384 → rounds to 6.4.",
    },
  },
  {
    id: "sigfig-016",
    topic: "significant-figures",
    subtopic: "rounding-mult-div",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Calculate 3.20 × 2.1 and report with the correct number of significant figures.",
      answer_type: "numeric",
      correct_answer: 6.7,
      explanation: "3.20 × 2.1 = 6.72. 2.1 has 2 sig figs (fewest), so round to 6.7.",
    },
  },
  {
    id: "sigfig-017",
    topic: "significant-figures",
    subtopic: "rounding-add-sub",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Calculate 15.32 + 4.1 + 3.784 and report with the correct number of decimal places.",
      answer_type: "numeric",
      correct_answer: 23.2,
      explanation: "15.32 + 4.1 + 3.784 = 23.204. 4.1 has 1 decimal place (fewest), so round to 23.2.",
    },
  },
  {
    id: "sigfig-018",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 500.?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "The decimal point after 500 makes the trailing zeros significant → 3 sig figs. Without the decimal, 500 would be ambiguous (1 sig fig).",
    },
  },
];
