import type { Question } from "@/lib/types";

export const SAMPLE_QUESTIONS: Question[] = [
  // ============================================================
  // FUNDAMENTALS (12 questions)
  // ============================================================
  {
    id: "fund-001",
    topic: "fundamentals",
    subtopic: "measurement",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Every measurement consists of two parts. What are they?",
      answer_type: "multiple-choice",
      correct_answer: "A number and a unit",
      choices: ["A number and a unit", "A number only", "A unit and an uncertainty", "A number, a unit, and a symbol"],
      explanation: "Every measurement = a number (magnitude) + a unit (what is being measured). For example, 25 mL has the number 25 and the unit mL.",
    },
  },
  {
    id: "fund-002",
    topic: "fundamentals",
    subtopic: "accuracy-vs-precision",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Four students measure the mass of a 10.00 g standard. Their results: 10.01, 10.02, 9.99, 10.00. These measurements are best described as:",
      answer_type: "multiple-choice",
      correct_answer: "Both accurate and precise",
      choices: ["Accurate but not precise", "Precise but not accurate", "Both accurate and precise", "Neither accurate nor precise"],
      explanation: "The values are close to the true value (10.00 g) → accurate. They are also close to each other (small spread) → precise.",
    },
  },
  {
    id: "fund-003",
    topic: "fundamentals",
    subtopic: "accuracy-vs-precision",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A student consistently gets 7.32 g for a sample whose true mass is 8.50 g. This is an example of:",
      answer_type: "multiple-choice",
      correct_answer: "Precise but not accurate",
      choices: ["Accurate but not precise", "Precise but not accurate", "Both accurate and precise", "Neither accurate nor precise"],
      explanation: "Consistent results = precise. But far from the true value (8.50 g) = not accurate. This often indicates a systematic error (e.g., uncalibrated balance).",
    },
  },
  {
    id: "fund-004",
    topic: "fundamentals",
    subtopic: "physical-chemical-properties",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Which of the following is a chemical property?",
      answer_type: "multiple-choice",
      correct_answer: "Iron rusts in moist air",
      choices: ["Iron rusts in moist air", "Iron has a density of 7.87 g/cm³", "Iron melts at 1538°C", "Iron is a gray metal"],
      explanation: "Rusting is a chemical change (new substance formed). Density, melting point, and color are physical properties — they describe the substance without changing its identity.",
    },
  },
  {
    id: "fund-005",
    topic: "fundamentals",
    subtopic: "physical-chemical-properties",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which process involves a chemical change?",
      answer_type: "multiple-choice",
      correct_answer: "Burning natural gas on a stove",
      choices: ["Boiling water to make steam", "Burning natural gas on a stove", "Dissolving salt in water", "Crushing a rock into powder"],
      explanation: "Burning natural gas (CH₄ + O₂ → CO₂ + H₂O) produces new substances — a chemical change. The others are physical changes: state change, dissolving, and size reduction.",
    },
  },
  {
    id: "fund-006",
    topic: "fundamentals",
    subtopic: "states-of-matter",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Which state of matter has a definite volume but takes the shape of its container?",
      answer_type: "multiple-choice",
      correct_answer: "Liquid",
      choices: ["Solid", "Liquid", "Gas", "Plasma"],
      explanation: "Solids: definite shape + volume. Liquids: indefinite shape + definite volume. Gases: indefinite shape + indefinite volume.",
    },
  },
  {
    id: "fund-007",
    topic: "fundamentals",
    subtopic: "atoms-molecules",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the relationship between atoms and molecules?",
      answer_type: "multiple-choice",
      correct_answer: "A molecule is two or more atoms bonded together",
      choices: ["A molecule is two or more atoms bonded together", "An atom is made of molecules", "Atoms and molecules are identical", "A molecule is a single atom"],
      explanation: "An atom is the smallest unit of an element. A molecule is two or more atoms chemically bonded (e.g., H₂O = 2 H atoms + 1 O atom).",
    },
  },
  {
    id: "fund-008",
    topic: "fundamentals",
    subtopic: "elements-compounds",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which of the following is a compound?",
      answer_type: "multiple-choice",
      correct_answer: "Carbon dioxide (CO₂)",
      choices: ["Carbon dioxide (CO₂)", "Oxygen (O₂)", "Iron (Fe)", "Helium (He)"],
      explanation: "A compound contains two or more different elements chemically combined. CO₂ has carbon AND oxygen. O₂, Fe, and He are elements (single type of atom).",
    },
  },
  {
    id: "fund-009",
    topic: "fundamentals",
    subtopic: "mixtures",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A mixture of salt dissolved in water is best classified as:",
      answer_type: "multiple-choice",
      correct_answer: "A homogeneous mixture (solution)",
      choices: ["A homogeneous mixture (solution)", "A heterogeneous mixture", "A compound", "A pure element"],
      explanation: "Salt water is uniform throughout → homogeneous mixture (solution). The salt and water retain their individual properties and can be separated by physical means (evaporation).",
    },
  },
  {
    id: "fund-010",
    topic: "fundamentals",
    subtopic: "mass-vs-weight",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "An astronaut has a mass of 70 kg on Earth. What is their mass on the Moon?",
      answer_type: "multiple-choice",
      correct_answer: "70 kg",
      choices: ["70 kg", "About 11.7 kg", "About 420 kg", "Zero"],
      explanation: "Mass is the amount of matter — it does not change with location. Weight changes due to gravity (Moon gravity ≈ 1/6 of Earth's), but mass stays 70 kg.",
    },
  },
  {
    id: "fund-011",
    topic: "fundamentals",
    subtopic: "scientific-method",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A hypothesis is best defined as:",
      answer_type: "multiple-choice",
      correct_answer: "A testable explanation for an observation",
      choices: ["A testable explanation for an observation", "A proven fact about nature", "An educated guess that cannot be tested", "A law of nature"],
      explanation: "A hypothesis is a proposed, testable explanation. After repeated testing and verification, a hypothesis may become a theory. A law describes what happens (not why).",
    },
  },
  {
    id: "fund-012",
    topic: "fundamentals",
    subtopic: "density",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "An object has a mass of 27.0 g and a volume of 10.0 mL. What is its density?",
      answer_type: "numeric",
      correct_answer: 2.7,
      explanation: "Density = mass / volume = 27.0 g / 10.0 mL = 2.70 g/mL. This is the density of aluminum.",
    },
  },

  // ============================================================
  // METRIC SYSTEM (12 questions)
  // ============================================================
  {
    id: "metric-001",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'kilo' (k) mean?",
      answer_type: "multiple-choice",
      correct_answer: "1000",
      choices: ["100", "1000", "0.01", "0.001"],
      explanation: "kilo = 10³ = 1000. So 1 kg = 1000 g, 1 km = 1000 m.",
    },
  },
  {
    id: "metric-002",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'milli' (m) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.001",
      choices: ["0.1", "0.01", "0.001", "0.000001"],
      explanation: "milli = 10⁻³ = 0.001. So 1 mL = 0.001 L, 1 mg = 0.001 g.",
    },
  },
  {
    id: "metric-003",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'micro' (µ) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.000001",
      choices: ["0.001", "0.0001", "0.000001", "0.000000001"],
      explanation: "micro (µ) = 10⁻⁶ = 0.000001. So 1 µg = 0.000001 g.",
    },
  },
  {
    id: "metric-004",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'nano' (n) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.000000001",
      choices: ["0.000001", "0.0000001", "0.000000001", "0.0000000001"],
      explanation: "nano (n) = 10⁻⁹ = 0.000000001. Used in nanotechnology — structures on the scale of atoms and molecules.",
    },
  },
  {
    id: "metric-005",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'centi' (c) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.01",
      choices: ["0.1", "0.01", "100", "0.001"],
      explanation: "centi = 10⁻² = 0.01. So 1 cm = 0.01 m. There are 100 cm in 1 m.",
    },
  },
  {
    id: "metric-006",
    topic: "metric-system",
    subtopic: "si-prefixes",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does the prefix 'deci' (d) mean?",
      answer_type: "multiple-choice",
      correct_answer: "0.1",
      choices: ["0.1", "10", "0.01", "1"],
      explanation: "deci = 10⁻¹ = 0.1. So 1 dm = 0.1 m. There are 10 dm in 1 m.",
    },
  },
  {
    id: "metric-007",
    topic: "metric-system",
    subtopic: "base-units",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the SI base unit for mass?",
      answer_type: "multiple-choice",
      correct_answer: "Kilogram (kg)",
      choices: ["Gram (g)", "Kilogram (kg)", "Pound (lb)", "Milligram (mg)"],
      explanation: "The SI base unit for mass is the kilogram (kg), not the gram. The gram is a derived unit (1/1000 of a kg).",
    },
  },
  {
    id: "metric-008",
    topic: "metric-system",
    subtopic: "base-units",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the SI base unit for length?",
      answer_type: "multiple-choice",
      correct_answer: "Meter (m)",
      choices: ["Foot (ft)", "Meter (m)", "Centimeter (cm)", "Kilometer (km)"],
      explanation: "The SI base unit for length is the meter (m). All other length units (km, cm, mm, etc.) are derived from the meter using prefixes.",
    },
  },
  {
    id: "metric-009",
    topic: "metric-system",
    subtopic: "base-units",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the SI base unit for temperature?",
      answer_type: "multiple-choice",
      correct_answer: "Kelvin (K)",
      choices: ["Celsius (°C)", "Kelvin (K)", "Fahrenheit (°F)", "Joule (J)"],
      explanation: "The SI base unit for temperature is the Kelvin (K). Celsius is commonly used but is not the SI base unit. K = °C + 273.15.",
    },
  },
  {
    id: "metric-010",
    topic: "metric-system",
    subtopic: "prefix-conversion",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Convert 2.5 g to mg.",
      answer_type: "numeric",
      correct_answer: 2500,
      explanation: "1 g = 1000 mg. So 2.5 g × 1000 mg/g = 2500 mg.",
    },
  },
  {
    id: "metric-011",
    topic: "metric-system",
    subtopic: "prefix-conversion",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Convert 375 mg to g.",
      answer_type: "numeric",
      correct_answer: 0.375,
      explanation: "1 mg = 0.001 g. So 375 mg × 0.001 g/mg = 0.375 g.",
    },
  },
  {
    id: "metric-012",
    topic: "metric-system",
    subtopic: "prefix-conversion",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 0.0450 km to cm.",
      answer_type: "numeric",
      correct_answer: 4500,
      explanation: "0.0450 km → 45.0 m (×1000) → 4500 cm (×100). Two steps: km→m, then m→cm.",
    },
  },

  // ============================================================
  // SIGNIFICANT FIGURES (18 questions)
  // ============================================================
  {
    id: "sigfig-001",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 3.45?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "All non-zero digits are significant. 3, 4, and 5 → 3 sig figs.",
    },
  },
  {
    id: "sigfig-002",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 2006?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "Non-zero digits are significant, and captive zeros (between non-zero digits) are significant. 2, 0, 0, 6 → 4 sig figs.",
    },
  },
  {
    id: "sigfig-003",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.0042?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "Leading zeros are NOT significant — they just locate the decimal. Only 4 and 2 count → 2 sig figs.",
    },
  },
  {
    id: "sigfig-004",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 8370.00?",
      answer_type: "numeric",
      correct_answer: 6,
      explanation: "Non-zero digits (8,3,7), captive zero (0), and trailing zeros after the decimal (0,0) are all significant → 6 sig figs.",
    },
  },
  {
    id: "sigfig-005",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 100.0?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "The 1, the two captive zeros, and the trailing zero after the decimal are all significant → 4 sig figs.",
    },
  },
  {
    id: "sigfig-006",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 4.0200?",
      answer_type: "numeric",
      correct_answer: 5,
      explanation: "4, 0 (captive), 2, 0 (trailing), 0 (trailing) — all significant → 5 sig figs.",
    },
  },
  {
    id: "sigfig-007",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.0005?",
      answer_type: "numeric",
      correct_answer: 1,
      explanation: "Leading zeros never count. Only the 5 is significant → 1 sig fig.",
    },
  },
  {
    id: "sigfig-008",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 10.030?",
      answer_type: "numeric",
      correct_answer: 5,
      explanation: "1, 0 (captive), 0 (captive), 3, and 0 (trailing after decimal) → 5 sig figs.",
    },
  },
  {
    id: "sigfig-009",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 25.0?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "2, 5, and the trailing 0 after the decimal → 3 sig figs.",
    },
  },
  {
    id: "sigfig-010",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.03040?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "Leading zeros don't count. 3, 0 (captive), 4, and 0 (trailing after decimal) → 4 sig figs.",
    },
  },
  {
    id: "sigfig-011",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.0100?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "Leading zeros don't count. 1 and the two trailing zeros after the decimal → 3 sig figs.",
    },
  },
  {
    id: "sigfig-012",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 1.007?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "1, 0 (captive), 0 (captive), 7 → 4 sig figs.",
    },
  },
  {
    id: "sigfig-013",
    topic: "significant-figures",
    subtopic: "rounding-mult-div",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "For 2.5 × 2.5, how many significant figures should the answer have?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "For multiplication/division: the result has the same number of sig figs as the factor with the fewest. Both have 2 sig figs → answer should have 2.",
    },
  },
  {
    id: "sigfig-014",
    topic: "significant-figures",
    subtopic: "rounding-add-sub",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "For 12.1 + 3.447, how many decimal places should the answer have?",
      answer_type: "numeric",
      correct_answer: 1,
      explanation: "For addition/subtraction: the result has the same number of decimal places as the term with the fewest. 12.1 has 1 decimal place → answer should have 1.",
    },
  },
  {
    id: "sigfig-015",
    topic: "significant-figures",
    subtopic: "rounding-mult-div",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "For 4.56 × 1.4, how many significant figures should the answer have?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "1.4 has 2 sig figs (fewest), so the answer should have 2 sig figs. 4.56 × 1.4 = 6.384 → rounds to 6.4.",
    },
  },
  {
    id: "sigfig-016",
    topic: "significant-figures",
    subtopic: "rounding-mult-div",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Calculate 3.20 × 2.1 and report with the correct number of significant figures.",
      answer_type: "numeric",
      correct_answer: 6.7,
      explanation: "3.20 × 2.1 = 6.72. 2.1 has 2 sig figs (fewest), so round to 6.7.",
    },
  },
  {
    id: "sigfig-017",
    topic: "significant-figures",
    subtopic: "rounding-add-sub",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Calculate 15.32 + 4.1 + 3.784 and report with the correct number of decimal places.",
      answer_type: "numeric",
      correct_answer: 23.2,
      explanation: "15.32 + 4.1 + 3.784 = 23.204. 4.1 has 1 decimal place (fewest), so round to 23.2.",
    },
  },
  {
    id: "sigfig-018",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 500.?",
      answer_type: "numeric",
      correct_answer: 3,
      explanation: "The decimal point after 500 makes the trailing zeros significant → 3 sig figs. Without the decimal, 500 would be ambiguous (1 sig fig).",
    },
  },

  // ============================================================
  // DIMENSIONAL ANALYSIS (14 questions — 6 solver, 8 quiz)
  // ============================================================
  {
    id: "diman-001",
    topic: "dimensional-analysis",
    subtopic: "single-step",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the core principle of dimensional analysis?",
      answer_type: "multiple-choice",
      correct_answer: "Units cancel out, leaving the desired unit",
      choices: [
        "Units cancel out, leaving the desired unit",
        "You multiply all numbers together",
        "You convert everything to metric first",
        "You add units together to get new units",
      ],
      explanation: "Dimensional analysis uses conversion factors arranged as fractions so unwanted units cancel (appear in both numerator and denominator), leaving only the target unit.",
    },
  },
  {
    id: "diman-002",
    topic: "dimensional-analysis",
    subtopic: "single-step",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "In the conversion factor (1000 m / 1 km), what does this represent?",
      answer_type: "multiple-choice",
      correct_answer: "An equality written as a fraction that equals 1",
      choices: [
        "An equality written as a fraction that equals 1",
        "A division problem to solve",
        "A ratio that equals 1000",
        "A formula for distance",
      ],
      explanation: "1000 m = 1 km, so (1000 m / 1 km) = 1. Multiplying by 1 doesn't change the value, only the units. This is the foundation of dimensional analysis.",
    },
  },
  {
    id: "diman-003",
    topic: "dimensional-analysis",
    subtopic: "single-step",
    mode: "solver",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Convert 5.00 km to meters.",
      given: [{ value: 5.00, unit: "km", sigfigs: 3 }],
      target_unit: "m",
      solution_chain: [
        { numerator: "1000 m", denominator: "1 km", numerator_value: 1000, denominator_value: 1 },
      ],
      final_answer: { value: 5000, unit: "m", sigfigs: 3, tolerance_pct: 1 },
      explanation: "5.00 km × (1000 m / 1 km) = 5000 m. The km units cancel, leaving meters. 3 sig figs from 5.00.",
    },
  },
  {
    id: "diman-004",
    topic: "dimensional-analysis",
    subtopic: "single-step",
    mode: "solver",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Convert 2500 g to kilograms.",
      given: [{ value: 2500, unit: "g", sigfigs: 2 }],
      target_unit: "kg",
      solution_chain: [
        { numerator: "1 kg", denominator: "1000 g", numerator_value: 1, denominator_value: 1000 },
      ],
      final_answer: { value: 2.5, unit: "kg", sigfigs: 2, tolerance_pct: 1 },
      explanation: "2500 g × (1 kg / 1000 g) = 2.5 kg. The g units cancel. 2500 has 2 sig figs (trailing zeros without decimal are ambiguous), so answer has 2.",
    },
  },
  {
    id: "diman-005",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Convert 3.50 km to cm.",
      given: [{ value: 3.50, unit: "km", sigfigs: 3 }],
      target_unit: "cm",
      solution_chain: [
        { numerator: "1000 m", denominator: "1 km", numerator_value: 1000, denominator_value: 1 },
        { numerator: "100 cm", denominator: "1 m", numerator_value: 100, denominator_value: 1 },
      ],
      final_answer: { value: 350000, unit: "cm", sigfigs: 3, tolerance_pct: 1 },
      explanation: "3.50 km × (1000 m / 1 km) × (100 cm / 1 m) = 350000 cm. Two conversion factors: km→m, then m→cm. 3 sig figs from 3.50.",
    },
  },
  {
    id: "diman-006",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Convert 0.0450 mm to µm (micrometers).",
      given: [{ value: 0.0450, unit: "mm", sigfigs: 3 }],
      target_unit: "µm",
      solution_chain: [
        { numerator: "1 m", denominator: "1000 mm", numerator_value: 1, denominator_value: 1000 },
        { numerator: "1000000 µm", denominator: "1 m", numerator_value: 1000000, denominator_value: 1 },
      ],
      final_answer: { value: 45.0, unit: "µm", sigfigs: 3, tolerance_pct: 1 },
      explanation: "0.0450 mm × (1 m / 1000 mm) × (1000000 µm / 1 m) = 45.0 µm. Two steps: mm→m, then m→µm. 3 sig figs from 0.0450.",
    },
  },
  {
    id: "diman-007",
    topic: "dimensional-analysis",
    subtopic: "imperial-to-metric",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 2.50 inches to cm. (1 inch = 2.54 cm)",
      given: [{ value: 2.50, unit: "in", sigfigs: 3 }],
      target_unit: "cm",
      solution_chain: [
        { numerator: "2.54 cm", denominator: "1 in", numerator_value: 2.54, denominator_value: 1 },
      ],
      final_answer: { value: 6.35, unit: "cm", sigfigs: 3, tolerance_pct: 1 },
      explanation: "2.50 in × (2.54 cm / 1 in) = 6.35 cm. The inch units cancel. 3 sig figs from 2.50 (2.54 is an exact definition).",
    },
  },
  {
    id: "diman-008",
    topic: "dimensional-analysis",
    subtopic: "imperial-to-metric",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 65.0 miles to km. (1 mile = 1.609 km)",
      given: [{ value: 65.0, unit: "mi", sigfigs: 3 }],
      target_unit: "km",
      solution_chain: [
        { numerator: "1.609 km", denominator: "1 mi", numerator_value: 1.609, denominator_value: 1 },
      ],
      final_answer: { value: 105, unit: "km", sigfigs: 3, tolerance_pct: 1 },
      explanation: "65.0 mi × (1.609 km / 1 mi) = 104.585 km → 105 km (3 sig figs from 65.0).",
    },
  },
  {
    id: "diman-009",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 55.0 mph (miles/hour) to m/s. (1 mile = 1.609 km, 1 hour = 3600 s)",
      given: [{ value: 55.0, unit: "mi/h", sigfigs: 3 }],
      target_unit: "m/s",
      solution_chain: [
        { numerator: "1.609 km", denominator: "1 mi", numerator_value: 1.609, denominator_value: 1 },
        { numerator: "1000 m", denominator: "1 km", numerator_value: 1000, denominator_value: 1 },
        { numerator: "1 h", denominator: "3600 s", numerator_value: 1, denominator_value: 3600 },
      ],
      final_answer: { value: 24.6, unit: "m/s", sigfigs: 3, tolerance_pct: 1 },
      explanation: "55.0 × 1.609 × 1000 / 3600 = 24.6 m/s. Three conversion factors: mi→km, km→m, h→s. 3 sig figs from 55.0.",
    },
  },
  {
    id: "diman-010",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 4.50 × 10⁴ µg to mg.",
      given: [{ value: 45000, unit: "µg", sigfigs: 3 }],
      target_unit: "mg",
      solution_chain: [
        { numerator: "1 g", denominator: "1000000 µg", numerator_value: 1, denominator_value: 1000000 },
        { numerator: "1000 mg", denominator: "1 g", numerator_value: 1000, denominator_value: 1 },
      ],
      final_answer: { value: 45.0, unit: "mg", sigfigs: 3, tolerance_pct: 1 },
      explanation: "45000 µg × (1 g / 1000000 µg) × (1000 mg / 1 g) = 45.0 mg. Two steps: µg→g, then g→mg. 3 sig figs from 4.50 × 10⁴.",
    },
  },
  {
    id: "diman-011",
    topic: "dimensional-analysis",
    subtopic: "concept",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "When setting up a dimensional analysis problem, how do you decide which unit goes in the numerator vs denominator of a conversion factor?",
      answer_type: "multiple-choice",
      correct_answer: "Put the unit you want to cancel in the denominator, and the unit you want to keep in the numerator",
      choices: [
        "Put the unit you want to cancel in the denominator, and the unit you want to keep in the numerator",
        "Always put the larger unit in the numerator",
        "Put the metric unit in the numerator and the English unit in the denominator",
        "It doesn't matter as long as both units are present",
      ],
      explanation: "The unit you want to eliminate must be in the opposite position (denominator) from where it currently appears, so it cancels. The desired unit goes in the numerator.",
    },
  },
  {
    id: "diman-012",
    topic: "dimensional-analysis",
    subtopic: "concept",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many conversion factors can be written from the equality 1 m = 100 cm?",
      answer_type: "multiple-choice",
      correct_answer: "Two: (100 cm / 1 m) and (1 m / 100 cm)",
      choices: [
        "One: (100 cm / 1 m)",
        "Two: (100 cm / 1 m) and (1 m / 100 cm)",
        "Three",
        "Only one, since 1 m = 100 cm is not a fraction",
      ],
      explanation: "Any equality A = B gives two conversion factors: (A/B) and (B/A). Both equal 1. You choose the one that cancels the unwanted unit.",
    },
  },
  {
    id: "diman-013",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 2.00 L to mL.",
      given: [{ value: 2.00, unit: "L", sigfigs: 3 }],
      target_unit: "mL",
      solution_chain: [
        { numerator: "1000 mL", denominator: "1 L", numerator_value: 1000, denominator_value: 1 },
      ],
      final_answer: { value: 2000, unit: "mL", sigfigs: 3, tolerance_pct: 1 },
      explanation: "2.00 L × (1000 mL / 1 L) = 2000 mL. Single step. 3 sig figs from 2.00.",
    },
  },
  {
    id: "diman-014",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Convert 0.750 L to µL.",
      given: [{ value: 0.750, unit: "L", sigfigs: 3 }],
      target_unit: "µL",
      solution_chain: [
        { numerator: "1000 mL", denominator: "1 L", numerator_value: 1000, denominator_value: 1 },
        { numerator: "1000 µL", denominator: "1 mL", numerator_value: 1000, denominator_value: 1 },
      ],
      final_answer: { value: 750000, unit: "µL", sigfigs: 3, tolerance_pct: 1 },
      explanation: "0.750 L × (1000 mL / 1 L) × (1000 µL / 1 mL) = 750000 µL. Two steps: L→mL, then mL→µL. 3 sig figs from 0.750.",
    },
  },

  // ============================================================
  // THE MOLE (14 questions — 8 solver, 6 quiz)
  // ============================================================
  {
    id: "mole-001",
    topic: "the-mole",
    subtopic: "avogadro-concept",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is Avogadro's number?",
      answer_type: "multiple-choice",
      correct_answer: "6.022 × 10²³",
      choices: ["6.022 × 10²³", "3.011 × 10²³", "1.204 × 10²⁴", "6.022 × 10²²"],
      explanation: "Avogadro's number = 6.022 × 10²³. This is the number of particles (atoms, molecules, ions) in exactly 1 mole of any substance.",
    },
  },
  {
    id: "mole-002",
    topic: "the-mole",
    subtopic: "avogadro-concept",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does 1 mole of any substance contain?",
      answer_type: "multiple-choice",
      correct_answer: "6.022 × 10²³ particles",
      choices: [
        "6.022 × 10²³ particles",
        "1 gram of the substance",
        "22.4 liters at any temperature",
        "12 particles",
      ],
      explanation: "1 mole = 6.022 × 10²³ particles (Avogadro's number). This is true for atoms, molecules, ions, or any counted entity.",
    },
  },
  {
    id: "mole-003",
    topic: "the-mole",
    subtopic: "mole-to-particles",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many atoms are in 2.50 moles of copper (Cu)?",
      given: [{ value: 2.50, unit: "mol", sigfigs: 3 }],
      target_unit: "atoms",
      solution_chain: [
        { numerator: "6.022e23 atoms", denominator: "1 mol", numerator_value: 6.022e23, denominator_value: 1 },
      ],
      final_answer: { value: 1.51e24, unit: "atoms", sigfigs: 3, tolerance_pct: 1 },
      explanation: "2.50 mol × (6.022 × 10²³ atoms / 1 mol) = 1.51 × 10²⁴ atoms. 3 sig figs from 2.50.",
    },
  },
  {
    id: "mole-004",
    topic: "the-mole",
    subtopic: "particles-to-mole",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many moles are in 1.20 × 10²⁴ molecules of H₂O?",
      given: [{ value: 1.2e24, unit: "molecules", sigfigs: 3 }],
      target_unit: "mol",
      solution_chain: [
        { numerator: "1 mol", denominator: "6.022e23 molecules", numerator_value: 1, denominator_value: 6.022e23 },
      ],
      final_answer: { value: 1.99, unit: "mol", sigfigs: 3, tolerance_pct: 1 },
      explanation: "1.20 × 10²⁴ molecules × (1 mol / 6.022 × 10²³ molecules) = 1.99 mol. 3 sig figs from 1.20 × 10²⁴.",
    },
  },
  {
    id: "mole-005",
    topic: "the-mole",
    subtopic: "mole-to-mass",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the mass of 3.00 moles of NaCl? (Molar mass of NaCl = 58.44 g/mol)",
      given: [{ value: 3.00, unit: "mol", sigfigs: 3 }],
      target_unit: "g",
      solution_chain: [
        { numerator: "58.44 g", denominator: "1 mol", numerator_value: 58.44, denominator_value: 1 },
      ],
      final_answer: { value: 175.32, unit: "g", sigfigs: 3, tolerance_pct: 1 },
      explanation: "3.00 mol × (58.44 g / 1 mol) = 175.32 g → 175 g. 3 sig figs from 3.00.",
    },
  },
  {
    id: "mole-006",
    topic: "the-mole",
    subtopic: "mass-to-mole",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many moles are in 50.0 g of NaOH? (Molar mass of NaOH = 40.00 g/mol)",
      given: [{ value: 50.0, unit: "g", sigfigs: 3 }],
      target_unit: "mol",
      solution_chain: [
        { numerator: "1 mol", denominator: "40.00 g", numerator_value: 1, denominator_value: 40.0 },
      ],
      final_answer: { value: 1.25, unit: "mol", sigfigs: 3, tolerance_pct: 1 },
      explanation: "50.0 g × (1 mol / 40.00 g) = 1.25 mol. 3 sig figs from 50.0.",
    },
  },
  {
    id: "mole-007",
    topic: "the-mole",
    subtopic: "mass-to-particles",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many molecules are in 18.0 g of H₂O? (Molar mass of H₂O = 18.02 g/mol)",
      given: [{ value: 18.0, unit: "g", sigfigs: 3 }],
      target_unit: "molecules",
      solution_chain: [
        { numerator: "1 mol", denominator: "18.02 g", numerator_value: 1, denominator_value: 18.02 },
        { numerator: "6.022e23 molecules", denominator: "1 mol", numerator_value: 6.022e23, denominator_value: 1 },
      ],
      final_answer: { value: 6.02e23, unit: "molecules", sigfigs: 3, tolerance_pct: 1 },
      explanation: "18.0 g × (1 mol / 18.02 g) × (6.022 × 10²³ molecules / 1 mol) = 6.02 × 10²³ molecules. Two steps: g→mol, then mol→molecules. 3 sig figs.",
    },
  },
  {
    id: "mole-008",
    topic: "the-mole",
    subtopic: "molar-mass",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the molar mass of CaCO₃? (Ca = 40.08, C = 12.01, O = 16.00 g/mol)",
      answer_type: "numeric",
      correct_answer: 100.09,
      explanation: "Ca(40.08) + C(12.01) + 3×O(16.00) = 40.08 + 12.01 + 48.00 = 100.09 g/mol.",
    },
  },
  {
    id: "mole-009",
    topic: "the-mole",
    subtopic: "molar-mass",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the molar mass of H₂SO₄? (H = 1.008, S = 32.07, O = 16.00 g/mol)",
      answer_type: "numeric",
      correct_answer: 98.086,
      explanation: "2×H(1.008) + S(32.07) + 4×O(16.00) = 2.016 + 32.07 + 64.00 = 98.086 g/mol.",
    },
  },
  {
    id: "mole-010",
    topic: "the-mole",
    subtopic: "mole-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "What is the mass of 0.500 moles of CH₄? (Molar mass of CH₄ = 16.04 g/mol)",
      given: [{ value: 0.500, unit: "mol", sigfigs: 3 }],
      target_unit: "g",
      solution_chain: [
        { numerator: "16.04 g", denominator: "1 mol", numerator_value: 16.04, denominator_value: 1 },
      ],
      final_answer: { value: 8.02, unit: "g", sigfigs: 3, tolerance_pct: 1 },
      explanation: "0.500 mol × (16.04 g / 1 mol) = 8.02 g. 3 sig figs from 0.500.",
    },
  },
  {
    id: "mole-011",
    topic: "the-mole",
    subtopic: "particles-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "What is the mass of 3.01 × 10²³ atoms of Fe? (Molar mass of Fe = 55.85 g/mol)",
      given: [{ value: 3.01e23, unit: "atoms", sigfigs: 3 }],
      target_unit: "g",
      solution_chain: [
        { numerator: "1 mol", denominator: "6.022e23 atoms", numerator_value: 1, denominator_value: 6.022e23 },
        { numerator: "55.85 g", denominator: "1 mol", numerator_value: 55.85, denominator_value: 1 },
      ],
      final_answer: { value: 27.9, unit: "g", sigfigs: 3, tolerance_pct: 1 },
      explanation: "3.01 × 10²³ atoms × (1 mol / 6.022 × 10²³) × (55.85 g / 1 mol) = 27.9 g. Two steps: atoms→mol, then mol→g. 3 sig figs.",
    },
  },
  {
    id: "mole-012",
    topic: "the-mole",
    subtopic: "avogadro-concept",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which contains more molecules: 1 mole of H₂O or 1 mole of CO₂?",
      answer_type: "multiple-choice",
      correct_answer: "They contain the same number of molecules",
      choices: [
        "1 mole of H₂O (lighter molecules)",
        "1 mole of CO₂ (heavier molecules)",
        "They contain the same number of molecules",
        "Cannot be determined without more information",
      ],
      explanation: "1 mole of ANY substance contains Avogadro's number (6.022 × 10²³) of particles. The type of molecule doesn't matter — only the mole count.",
    },
  },
  {
    id: "mole-013",
    topic: "the-mole",
    subtopic: "mole-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many grams are in 1.50 moles of K₂SO₄? (Molar mass = 174.26 g/mol)",
      given: [{ value: 1.50, unit: "mol", sigfigs: 3 }],
      target_unit: "g",
      solution_chain: [
        { numerator: "174.26 g", denominator: "1 mol", numerator_value: 174.26, denominator_value: 1 },
      ],
      final_answer: { value: 261, unit: "g", sigfigs: 3, tolerance_pct: 1 },
      explanation: "1.50 mol × (174.26 g / 1 mol) = 261.39 g → 261 g. 3 sig figs from 1.50.",
    },
  },
  {
    id: "mole-014",
    topic: "the-mole",
    subtopic: "molar-mass",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is 'molar mass'?",
      answer_type: "multiple-choice",
      correct_answer: "The mass of one mole of a substance in grams",
      choices: [
        "The mass of one mole of a substance in grams",
        "The mass of one atom in grams",
        "The mass of one molecule in amu",
        "The number of atoms in one gram",
      ],
      explanation: "Molar mass = mass of 1 mole of a substance, expressed in g/mol. It numerically equals the atomic/molecular weight from the periodic table.",
    },
  },

  // ============================================================
  // STOICHIOMETRY (14 questions — 8 solver, 6 quiz)
  // ============================================================
  {
    id: "stoic-001",
    topic: "stoichiometry",
    subtopic: "balanced-equations",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What does a balanced chemical equation tell us about the mole ratios?",
      answer_type: "multiple-choice",
      correct_answer: "The coefficients give the mole ratio of reactants and products",
      choices: [
        "The coefficients give the mole ratio of reactants and products",
        "The subscripts give the mole ratio",
        "The charges give the mole ratio",
        "The states (s, l, g, aq) give the mole ratio",
      ],
      explanation: "Coefficients in a balanced equation represent mole ratios. For 2H₂ + O₂ → 2H₂O, the ratio is 2 mol H₂ : 1 mol O₂ : 2 mol H₂O.",
    },
  },
  {
    id: "stoic-002",
    topic: "stoichiometry",
    subtopic: "balanced-equations",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Balance: __ N₂ + __ H₂ → __ NH₃. What are the coefficients?",
      answer_type: "multiple-choice",
      correct_answer: "1, 3, 2",
      choices: ["1, 3, 2", "1, 2, 3", "2, 3, 2", "1, 1, 2"],
      explanation: "N₂ + 3H₂ → 2NH₃. Left: 2 N, 6 H. Right: 2 N, 6 H. Balanced!",
    },
  },
  {
    id: "stoic-003",
    topic: "stoichiometry",
    subtopic: "balanced-equations",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Balance: __ C₃H₈ + __ O₂ → __ CO₂ + __ H₂O. What are the coefficients?",
      answer_type: "multiple-choice",
      correct_answer: "1, 5, 3, 4",
      choices: ["1, 5, 3, 4", "1, 3, 3, 4", "2, 7, 6, 8", "1, 5, 4, 3"],
      explanation: "C₃H₈ + 5O₂ → 3CO₂ + 4H₂O. Left: 3 C, 8 H, 10 O. Right: 3 C, 8 H, 10 O. Balanced!",
    },
  },
  {
    id: "stoic-004",
    topic: "stoichiometry",
    subtopic: "mole-to-mole",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "In the reaction 2H₂ + O₂ → 2H₂O, how many moles of H₂O are produced from 4.0 moles of H₂?",
      given: [{ value: 4.0, unit: "mol H2", sigfigs: 2 }],
      target_unit: "mol H2O",
      solution_chain: [
        { numerator: "2 mol H2O", denominator: "2 mol H2", numerator_value: 2, denominator_value: 2 },
      ],
      final_answer: { value: 4.0, unit: "mol H2O", sigfigs: 2, tolerance_pct: 1 },
      explanation: "4.0 mol H₂ × (2 mol H₂O / 2 mol H₂) = 4.0 mol H₂O. The mole ratio from the balanced equation is 2:2 = 1:1. 2 sig figs from 4.0.",
    },
  },
  {
    id: "stoic-005",
    topic: "stoichiometry",
    subtopic: "mole-to-mole",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "In the reaction N₂ + 3H₂ → 2NH₃, how many moles of NH₃ form from 1.50 moles of N₂?",
      given: [{ value: 1.50, unit: "mol N2", sigfigs: 3 }],
      target_unit: "mol NH3",
      solution_chain: [
        { numerator: "2 mol NH3", denominator: "1 mol N2", numerator_value: 2, denominator_value: 1 },
      ],
      final_answer: { value: 3.00, unit: "mol NH3", sigfigs: 3, tolerance_pct: 1 },
      explanation: "1.50 mol N₂ × (2 mol NH₃ / 1 mol N₂) = 3.00 mol NH₃. Mole ratio 2:1 from balanced equation. 3 sig figs.",
    },
  },
  {
    id: "stoic-006",
    topic: "stoichiometry",
    subtopic: "mass-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "In 2Na + Cl₂ → 2NaCl, how many grams of NaCl are produced from 10.0 g of Na? (Molar mass: Na = 22.99, NaCl = 58.44 g/mol)",
      given: [{ value: 10.0, unit: "g Na", sigfigs: 3 }],
      target_unit: "g NaCl",
      solution_chain: [
        { numerator: "1 mol Na", denominator: "22.99 g Na", numerator_value: 1, denominator_value: 22.99 },
        { numerator: "2 mol NaCl", denominator: "2 mol Na", numerator_value: 2, denominator_value: 2 },
        { numerator: "58.44 g NaCl", denominator: "1 mol NaCl", numerator_value: 58.44, denominator_value: 1 },
      ],
      final_answer: { value: 25.4, unit: "g NaCl", sigfigs: 3, tolerance_pct: 1 },
      explanation: "10.0 g Na × (1 mol Na / 22.99 g) × (2 mol NaCl / 2 mol Na) × (58.44 g NaCl / 1 mol) = 25.4 g NaCl. Three steps: g→mol, mole ratio, mol→g. 3 sig figs.",
    },
  },
  {
    id: "stoic-007",
    topic: "stoichiometry",
    subtopic: "mass-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "In CH₄ + 2O₂ → CO₂ + 2H₂O, how many grams of CO₂ are produced from 25.0 g of CH₄? (Molar mass: CH₄ = 16.04, CO₂ = 44.01 g/mol)",
      given: [{ value: 25.0, unit: "g CH4", sigfigs: 3 }],
      target_unit: "g CO2",
      solution_chain: [
        { numerator: "1 mol CH4", denominator: "16.04 g CH4", numerator_value: 1, denominator_value: 16.04 },
        { numerator: "1 mol CO2", denominator: "1 mol CH4", numerator_value: 1, denominator_value: 1 },
        { numerator: "44.01 g CO2", denominator: "1 mol CO2", numerator_value: 44.01, denominator_value: 1 },
      ],
      final_answer: { value: 68.5, unit: "g CO2", sigfigs: 3, tolerance_pct: 1 },
      explanation: "25.0 g CH₄ × (1 mol / 16.04 g) × (1 mol CO₂ / 1 mol CH₄) × (44.01 g / 1 mol) = 68.5 g CO₂. 3 sig figs from 25.0.",
    },
  },
  {
    id: "stoic-008",
    topic: "stoichiometry",
    subtopic: "limiting-reactant",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is a limiting reactant?",
      answer_type: "multiple-choice",
      correct_answer: "The reactant that runs out first and limits the amount of product",
      choices: [
        "The reactant that runs out first and limits the amount of product",
        "The reactant with the smallest mass",
        "The reactant with the largest molar mass",
        "The reactant that is left over after the reaction",
      ],
      explanation: "The limiting reactant is consumed first and determines the maximum amount of product. The excess reactant is left over.",
    },
  },
  {
    id: "stoic-009",
    topic: "stoichiometry",
    subtopic: "limiting-reactant",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "For 2H₂ + O₂ → 2H₂O, if you have 5 mol H₂ and 2 mol O₂, which is the limiting reactant?",
      answer_type: "multiple-choice",
      correct_answer: "O₂ is limiting",
      choices: ["H₂ is limiting", "O₂ is limiting", "Both are limiting", "Neither is limiting"],
      explanation: "2 mol O₂ can react with 4 mol H₂ (ratio 2:1), and we have 5 mol H₂ — so H₂ is in excess. O₂ runs out first → O₂ is limiting.",
    },
  },
  {
    id: "stoic-010",
    topic: "stoichiometry",
    subtopic: "percent-yield",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is percent yield?",
      answer_type: "multiple-choice",
      correct_answer: "(actual yield / theoretical yield) × 100%",
      choices: [
        "(actual yield / theoretical yield) × 100%",
        "(theoretical yield / actual yield) × 100%",
        "(actual yield + theoretical yield) × 100%",
        "(actual yield × theoretical yield) / 100",
      ],
      explanation: "Percent yield = (actual yield / theoretical yield) × 100%. Theoretical yield is the max possible from stoichiometry; actual yield is what you actually get.",
    },
  },
  {
    id: "stoic-011",
    topic: "stoichiometry",
    subtopic: "percent-yield",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A reaction has a theoretical yield of 50.0 g but only 42.0 g is actually produced. What is the percent yield?",
      answer_type: "numeric",
      correct_answer: 84.0,
      explanation: "(42.0 / 50.0) × 100% = 84.0%. 3 sig figs.",
    },
  },
  {
    id: "stoic-012",
    topic: "stoichiometry",
    subtopic: "mass-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "In 4Fe + 3O₂ → 2Fe₂O₃, how many grams of Fe₂O₃ form from 30.0 g of Fe? (Molar mass: Fe = 55.85, Fe₂O₃ = 159.70 g/mol)",
      given: [{ value: 30.0, unit: "g Fe", sigfigs: 3 }],
      target_unit: "g Fe2O3",
      solution_chain: [
        { numerator: "1 mol Fe", denominator: "55.85 g Fe", numerator_value: 1, denominator_value: 55.85 },
        { numerator: "2 mol Fe2O3", denominator: "4 mol Fe", numerator_value: 2, denominator_value: 4 },
        { numerator: "159.70 g Fe2O3", denominator: "1 mol Fe2O3", numerator_value: 159.7, denominator_value: 1 },
      ],
      final_answer: { value: 42.9, unit: "g Fe2O3", sigfigs: 3, tolerance_pct: 1 },
      explanation: "30.0 g Fe × (1 mol / 55.85 g) × (2 mol Fe₂O₃ / 4 mol Fe) × (159.70 g / 1 mol) = 42.9 g Fe₂O₃. 3 sig figs.",
    },
  },
  {
    id: "stoic-013",
    topic: "stoichiometry",
    subtopic: "mole-to-mole",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "In C₃H₈ + 5O₂ → 3CO₂ + 4H₂O, how many moles of O₂ are needed to react with 2.50 moles of C₃H₈?",
      given: [{ value: 2.50, unit: "mol C3H8", sigfigs: 3 }],
      target_unit: "mol O2",
      solution_chain: [
        { numerator: "5 mol O2", denominator: "1 mol C3H8", numerator_value: 5, denominator_value: 1 },
      ],
      final_answer: { value: 12.5, unit: "mol O2", sigfigs: 3, tolerance_pct: 1 },
      explanation: "2.50 mol C₃H₈ × (5 mol O₂ / 1 mol C₃H₈) = 12.5 mol O₂. Mole ratio 5:1 from balanced equation. 3 sig figs.",
    },
  },
  {
    id: "stoic-014",
    topic: "stoichiometry",
    subtopic: "limiting-reactant",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "For 2H₂ + O₂ → 2H₂O, if you have 5 mol H₂ and 3 mol O₂, which is the limiting reactant?",
      answer_type: "multiple-choice",
      correct_answer: "H₂ is limiting",
      choices: ["H₂ is limiting", "O₂ is limiting", "Both are consumed completely", "Cannot be determined"],
      explanation: "5 mol H₂ needs 2.5 mol O₂ (ratio 2:1). We have 3 mol O₂, so O₂ is in excess. H₂ runs out first → H₂ is limiting.",
    },
  },

  // ============================================================
  // MOLARITY & DILUTIONS (14 questions — 8 solver, 6 quiz)
  // ============================================================
  {
    id: "molarity-001",
    topic: "molarity-dilutions",
    subtopic: "molarity-definition",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the definition of molarity (M)?",
      answer_type: "multiple-choice",
      correct_answer: "Moles of solute per liter of solution",
      choices: [
        "Moles of solute per liter of solution",
        "Grams of solute per liter of solvent",
        "Moles of solute per kg of solvent",
        "Grams of solute per mL of solution",
      ],
      explanation: "Molarity (M) = moles of solute / liters of solution. Unit is mol/L or M. Note: it's liters of SOLUTION, not solvent.",
    },
  },
  {
    id: "molarity-002",
    topic: "molarity-dilutions",
    subtopic: "molarity-calculation",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the molarity of a solution containing 0.500 mol of NaCl dissolved in 2.50 L of solution?",
      given: [{ value: 0.500, unit: "mol", sigfigs: 3 }],
      target_unit: "mol/L",
      solution_chain: [
        { numerator: "1 L", denominator: "2.50 L", numerator_value: 1, denominator_value: 2.50 },
      ],
      final_answer: { value: 0.200, unit: "mol/L", sigfigs: 3, tolerance_pct: 1 },
      explanation: "M = mol / L = 0.500 mol / 2.50 L = 0.200 M. 3 sig figs.",
    },
  },
  {
    id: "molarity-003",
    topic: "molarity-dilutions",
    subtopic: "molarity-calculation",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many moles of KCl are in 500.0 mL of a 0.250 M KCl solution?",
      given: [{ value: 500.0, unit: "mL", sigfigs: 4 }],
      target_unit: "mol",
      solution_chain: [
        { numerator: "1 L", denominator: "1000 mL", numerator_value: 1, denominator_value: 1000 },
        { numerator: "0.250 mol", denominator: "1 L", numerator_value: 0.25, denominator_value: 1 },
      ],
      final_answer: { value: 0.125, unit: "mol", sigfigs: 3, tolerance_pct: 1 },
      explanation: "500.0 mL × (1 L / 1000 mL) × (0.250 mol / 1 L) = 0.125 mol. Two steps: mL→L, then L→mol using molarity. 3 sig figs (limited by 0.250 M).",
    },
  },
  {
    id: "molarity-004",
    topic: "molarity-dilutions",
    subtopic: "molarity-calculation",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "What is the molarity of a solution made by dissolving 5.85 g of NaCl in water to make 250.0 mL of solution? (Molar mass of NaCl = 58.44 g/mol)",
      given: [{ value: 5.85, unit: "g", sigfigs: 3 }],
      target_unit: "mol/L",
      solution_chain: [
        { numerator: "1 mol", denominator: "58.44 g", numerator_value: 1, denominator_value: 58.44 },
        { numerator: "1000 mL", denominator: "250.0 mL", numerator_value: 1000, denominator_value: 250 },
      ],
      final_answer: { value: 0.400, unit: "mol/L", sigfigs: 3, tolerance_pct: 1 },
      explanation: "5.85 g ÷ 58.44 g/mol = 0.1001 mol. 250.0 mL = 0.2500 L. M = 0.1001 mol / 0.2500 L = 0.400 M. 3 sig figs from 5.85 g.",
    },
  },
  {
    id: "molarity-005",
    topic: "molarity-dilutions",
    subtopic: "dilution",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What is the dilution equation?",
      answer_type: "multiple-choice",
      correct_answer: "M₁V₁ = M₂V₂",
      choices: ["M₁V₁ = M₂V₂", "M₁ + V₁ = M₂ + V₂", "M₁/V₁ = M₂/V₂", "M₁V₁ = M₂/V₂"],
      explanation: "M₁V₁ = M₂V₂. The moles of solute stay the same during dilution (only solvent is added). M₁V₁ = moles before = moles after = M₂V₂.",
    },
  },
  {
    id: "molarity-006",
    topic: "molarity-dilutions",
    subtopic: "dilution",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "When you dilute a solution by adding water, what stays the same?",
      answer_type: "multiple-choice",
      correct_answer: "The moles of solute",
      choices: [
        "The moles of solute",
        "The molarity of the solution",
        "The volume of the solution",
        "The concentration of the solution",
      ],
      explanation: "Dilution adds solvent, not solute. The moles of solute don't change — only the volume increases and the concentration (molarity) decreases.",
    },
  },
  {
    id: "molarity-007",
    topic: "molarity-dilutions",
    subtopic: "dilution",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the final concentration when 100.0 mL of 0.500 M HCl is diluted to 250.0 mL?",
      given: [{ value: 100.0, unit: "mL", sigfigs: 4 }],
      target_unit: "M",
      solution_chain: [
        { numerator: "0.500 M", denominator: "1", numerator_value: 0.5, denominator_value: 1 },
        { numerator: "100.0 mL", denominator: "250.0 mL", numerator_value: 100, denominator_value: 250 },
      ],
      final_answer: { value: 0.200, unit: "M", sigfigs: 3, tolerance_pct: 1 },
      explanation: "M₁V₁ = M₂V₂ → M₂ = (0.500 M × 100.0 mL) / 250.0 mL = 0.200 M. 3 sig figs (limited by 0.500).",
    },
  },
  {
    id: "molarity-008",
    topic: "molarity-dilutions",
    subtopic: "dilution",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many mL of 6.00 M HCl are needed to make 500.0 mL of 1.50 M HCl?",
      given: [{ value: 500.0, unit: "mL", sigfigs: 4 }],
      target_unit: "mL",
      solution_chain: [
        { numerator: "1.50 M", denominator: "6.00 M", numerator_value: 1.5, denominator_value: 6 },
        { numerator: "500.0 mL", denominator: "1", numerator_value: 500, denominator_value: 1 },
      ],
      final_answer: { value: 125, unit: "mL", sigfigs: 3, tolerance_pct: 1 },
      explanation: "M₁V₁ = M₂V₂ → V₁ = (1.50 M × 500.0 mL) / 6.00 M = 125 mL. 3 sig figs (limited by 1.50 and 6.00).",
    },
  },
  {
    id: "molarity-009",
    topic: "molarity-dilutions",
    subtopic: "molarity-calculation",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many grams of sugar (C₆H₁₂O₆, molar mass = 180.16 g/mol) are needed to make 150.0 mL of 0.200 M solution?",
      given: [{ value: 150.0, unit: "mL", sigfigs: 4 }],
      target_unit: "g",
      solution_chain: [
        { numerator: "1 L", denominator: "1000 mL", numerator_value: 1, denominator_value: 1000 },
        { numerator: "0.200 mol", denominator: "1 L", numerator_value: 0.2, denominator_value: 1 },
        { numerator: "180.16 g", denominator: "1 mol", numerator_value: 180.16, denominator_value: 1 },
      ],
      final_answer: { value: 5.40, unit: "g", sigfigs: 3, tolerance_pct: 1 },
      explanation: "150.0 mL × (1 L / 1000 mL) × (0.200 mol / 1 L) × (180.16 g / 1 mol) = 5.40 g. Three steps: mL→L, L→mol, mol→g. 3 sig figs from 0.200.",
    },
  },
  {
    id: "molarity-010",
    topic: "molarity-dilutions",
    subtopic: "dilution",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "If you dilute 50.0 mL of 2.0 M NaOH to a final volume of 200.0 mL, what is the new concentration?",
      answer_type: "numeric",
      correct_answer: 0.50,
      explanation: "M₁V₁ = M₂V₂ → M₂ = (2.0 M × 50.0 mL) / 200.0 mL = 0.50 M. 2 sig figs from 2.0.",
    },
  },
  {
    id: "molarity-011",
    topic: "molarity-dilutions",
    subtopic: "molarity-definition",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the difference between solute and solvent?",
      answer_type: "multiple-choice",
      correct_answer: "Solute is dissolved; solvent does the dissolving",
      choices: [
        "Solute is dissolved; solvent does the dissolving",
        "Solute is the liquid; solvent is the solid",
        "Solute and solvent are the same thing",
        "Solvent is dissolved; solute does the dissolving",
      ],
      explanation: "In salt water, salt is the solute (dissolved substance) and water is the solvent (dissolving medium). The result is a solution.",
    },
  },
  {
    id: "molarity-012",
    topic: "molarity-dilutions",
    subtopic: "molarity-calculation",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A solution has 0.100 mol of solute in 400 mL. What is the molarity?",
      answer_type: "numeric",
      correct_answer: 0.250,
      explanation: "M = 0.100 mol / 0.400 L = 0.250 M. Remember to convert mL to L first! 3 sig figs.",
    },
  },
  {
    id: "molarity-013",
    topic: "molarity-dilutions",
    subtopic: "dilution",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "A stock solution is 12.0 M HCl. How would you prepare 250.0 mL of 3.00 M HCl from this stock?",
      given: [{ value: 250.0, unit: "mL", sigfigs: 4 }],
      target_unit: "mL",
      solution_chain: [
        { numerator: "3.00 M", denominator: "12.0 M", numerator_value: 3, denominator_value: 12 },
        { numerator: "250.0 mL", denominator: "1", numerator_value: 250, denominator_value: 1 },
      ],
      final_answer: { value: 62.5, unit: "mL", sigfigs: 3, tolerance_pct: 1 },
      explanation: "V₁ = (M₂V₂) / M₁ = (3.00 M × 250.0 mL) / 12.0 M = 62.5 mL. Measure 62.5 mL of 12.0 M HCl and dilute to 250.0 mL total. 3 sig figs.",
    },
  },
  {
    id: "molarity-014",
    topic: "molarity-dilutions",
    subtopic: "molarity-calculation",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many mL of 0.150 M NaOH are needed to provide 0.0300 mol of NaOH?",
      given: [{ value: 0.0300, unit: "mol", sigfigs: 3 }],
      target_unit: "mL",
      solution_chain: [
        { numerator: "1 L", denominator: "0.150 mol", numerator_value: 1, denominator_value: 0.15 },
        { numerator: "1000 mL", denominator: "1 L", numerator_value: 1000, denominator_value: 1 },
      ],
      final_answer: { value: 200, unit: "mL", sigfigs: 3, tolerance_pct: 1 },
      explanation: "0.0300 mol × (1 L / 0.150 mol) × (1000 mL / 1 L) = 200 mL. Two steps: mol→L using molarity, then L→mL. 3 sig figs.",
    },
  },
  // ============================================================
  // NEW QUESTIONS FROM CHEM 121 PDF CONTENT (Aug 13, 2026)
  // ============================================================

  // --- FUNDAMENTALS: +8 questions (12 → 20) ---
  {
    id: "fund-013",
    topic: "fundamentals",
    subtopic: "states-of-matter",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "At the molecular level, how are particles arranged in a solid?",
      answer_type: "multiple-choice",
      correct_answer: "Packed closely, organized, small vibrations in place",
      choices: [
        "Packed closely, organized, small vibrations in place",
        "Close together but disorganized, can slip past each other",
        "Far apart and not touching, high kinetic energy",
        "Randomly distributed with moderate kinetic energy",
      ],
      explanation: "In a solid, particles are packed closely in an organized arrangement and only vibrate in place. Liquids are close but disorganized; gases are far apart with high kinetic energy.",
    },
  },
  {
    id: "fund-014",
    topic: "fundamentals",
    subtopic: "states-of-matter",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Which state of matter has particles with the highest kinetic energy?",
      answer_type: "multiple-choice",
      correct_answer: "Gas",
      choices: ["Solid", "Liquid", "Gas", "All have the same kinetic energy"],
      explanation: "Gas particles have the highest kinetic energy — they are far apart, not touching, and move freely at high speeds.",
    },
  },
  {
    id: "fund-015",
    topic: "fundamentals",
    subtopic: "mole-vs-molarity",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the difference between a mole and molarity?",
      answer_type: "multiple-choice",
      correct_answer: "A mole is a quantity (6.02 × 10²³); molarity is a concentration (moles per liter)",
      choices: [
        "A mole is a quantity (6.02 × 10²³); molarity is a concentration (moles per liter)",
        "A mole is a mass; molarity is a volume",
        "They are the same thing expressed in different units",
        "A mole is a concentration; molarity is a quantity",
      ],
      explanation: "A mole is a count of particles (like a dozen = 12, a mole = 6.02 × 10²³). Molarity is a concentration: moles per liter of solution. 1.0 mole NaCl is a specific amount; 1.0 M NaCl depends on volume to determine the amount.",
    },
  },
  {
    id: "fund-016",
    topic: "fundamentals",
    subtopic: "mole-vs-molarity",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Is 1.0 mole of NaCl the same as 1.0 molar NaCl?",
      answer_type: "multiple-choice",
      correct_answer: "No — 1.0 mole is a specific amount; 1.0 M depends on volume",
      choices: [
        "Yes, they are the same",
        "No — 1.0 mole is a specific amount; 1.0 M depends on volume",
        "No — 1.0 M is always more than 1.0 mole",
        "No — 1.0 mole is always more than 1.0 M",
      ],
      explanation: "1.0 mole NaCl = 6.02 × 10²³ molecules (a specific amount). 1.0 M NaCl = 1.0 mol/L. If you have 0.5 L of 1.0 M NaCl, you only have 0.5 mole. Concentration doesn't tell you the amount without also knowing the volume.",
    },
  },
  {
    id: "fund-017",
    topic: "fundamentals",
    subtopic: "density",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Diamond has a density of 3.50–3.53 g/cm³ and cubic zirconia has 5.65–5.95 g/cm³. A 1.75 carat stone displaces 99.5 µL. Is it diamond or zirconia? (1 carat = 200 mg; 1 mL = 1 cm³)",
      answer_type: "multiple-choice",
      correct_answer: "Diamond",
      choices: ["Diamond", "Cubic zirconia", "Cannot be determined", "Both are possible"],
      explanation: "1.75 carat × 200 mg/carat = 350 mg = 0.350 g. Volume = 99.5 µL = 0.0995 mL = 0.0995 cm³. Density = 0.350/0.0995 = 3.52 g/cm³ → matches diamond (3.50–3.53).",
    },
  },
  {
    id: "fund-018",
    topic: "fundamentals",
    subtopic: "precision-accuracy",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Using the dart board analogy, which scenario shows good precision but poor accuracy?",
      answer_type: "multiple-choice",
      correct_answer: "Darts clustered tightly in the upper-left, far from bullseye",
      choices: [
        "Darts clustered tightly in the upper-left, far from bullseye",
        "Darts scattered evenly around the bullseye",
        "Darts clustered tightly in the bullseye",
        "Darts scattered all over the board",
      ],
      explanation: "Tight clustering = precise (reproducible). Far from bullseye = not accurate. This pattern indicates a systematic error (like an uncalibrated instrument). Scattered around bullseye = accurate but not precise.",
    },
  },
  {
    id: "fund-019",
    topic: "fundamentals",
    subtopic: "atomic-structure",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the difference between an orbital and an orbit?",
      answer_type: "multiple-choice",
      correct_answer: "An orbital is a probability region; an orbit is a fixed path (outdated model)",
      choices: [
        "An orbital is a probability region; an orbit is a fixed path (outdated model)",
        "They are the same thing with different names",
        "An orbit is modern; an orbital is outdated",
        "An orbital is a fixed path; an orbit is a probability region",
      ],
      explanation: "An orbital is the space with ~95% probability of finding an electron (quantum model). An orbit is a specific fixed path (Bohr model, outdated). You cannot know exactly where an electron is in an orbital.",
    },
  },
  {
    id: "fund-020",
    topic: "fundamentals",
    subtopic: "atomic-structure",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Why do we treat electrons as if they have no mass when calculating the mass of an isotope?",
      answer_type: "multiple-choice",
      correct_answer: "Electron mass is ~1/1836 of a proton — negligible at sig fig precision",
      choices: [
        "Electrons are truly massless",
        "Electron mass is ~1/1836 of a proton — negligible at sig fig precision",
        "Electrons are outside the nucleus so don't contribute",
        "Electron mass cancels out in calculations",
      ],
      explanation: "Electrons do have mass (~1/1836 of a proton). For Carbon-12: 6(1) + 6(1) + 6(0.0005) = 12.003 ≈ 12 amu. The electron contribution is lost to significant figures.",
    },
  },

  // --- METRIC SYSTEM: +8 questions (12 → 20) ---
  {
    id: "metric-013",
    topic: "metric-system",
    subtopic: "unit-identification",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What quantity does the unit 'mg' measure?",
      answer_type: "multiple-choice",
      correct_answer: "Mass",
      choices: ["Mass", "Volume", "Length", "Concentration"],
      explanation: "mg = milligram. The base unit gram (g) measures mass. The prefix milli- means 10⁻³.",
    },
  },
  {
    id: "metric-014",
    topic: "metric-system",
    subtopic: "unit-identification",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "What quantity does the unit 'cm³' measure?",
      answer_type: "multiple-choice",
      correct_answer: "Volume",
      choices: ["Volume", "Length", "Mass", "Concentration"],
      explanation: "cm³ (cubic centimeters) measures volume. 1 cm³ = 1 mL by definition. Length cubed gives volume.",
    },
  },
  {
    id: "metric-015",
    topic: "metric-system",
    subtopic: "unit-identification",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What quantity does the unit 'µg/L' measure?",
      answer_type: "multiple-choice",
      correct_answer: "Concentration",
      choices: ["Concentration", "Mass", "Volume", "Length"],
      explanation: "µg/L = micrograms per liter. Mass per volume = concentration. This is similar to ppm (parts per million) for dilute aqueous solutions.",
    },
  },
  {
    id: "metric-016",
    topic: "metric-system",
    subtopic: "si-abbreviations",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the correct SI abbreviation for millimolar?",
      answer_type: "multiple-choice",
      correct_answer: "mM",
      choices: ["mM", "mm", "M", "mol"],
      explanation: "mM = millimolar = mmol/L = 10⁻³ M. Note: mm = millimeter (length), M = molarity (mol/L), mol = mole (quantity).",
    },
  },
  {
    id: "metric-017",
    topic: "metric-system",
    subtopic: "si-abbreviations",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What is the correct SI abbreviation for micromolar?",
      answer_type: "multiple-choice",
      correct_answer: "µM",
      choices: ["µM", "mM", "µmol", "µg"],
      explanation: "µM = micromolar = µmol/L = 10⁻⁶ M. The prefix micro- (µ) means 10⁻⁶.",
    },
  },
  {
    id: "metric-018",
    topic: "metric-system",
    subtopic: "conversion-ratios",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many mg are in 1 kg?",
      answer_type: "numeric",
      correct_answer: 1000000,
      explanation: "1 kg = 1000 g, and 1 g = 1000 mg, so 1 kg = 1,000,000 mg = 10⁶ mg. This is a 6-order-of-magnitude conversion.",
    },
  },
  {
    id: "metric-019",
    topic: "metric-system",
    subtopic: "conversion-ratios",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many µL are in 1 mL?",
      answer_type: "numeric",
      correct_answer: 1000,
      explanation: "1 mL = 10⁻³ L and 1 µL = 10⁻⁶ L, so 1 mL = 1000 µL. The conversion factor is 1000 µL / 1 mL.",
    },
  },
  {
    id: "metric-020",
    topic: "metric-system",
    subtopic: "conversion-ratios",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many nm are in 1 m? (Write as a number, not scientific notation)",
      answer_type: "numeric",
      correct_answer: 1000000000,
      explanation: "1 nm = 10⁻⁹ m, so 1 m = 10⁹ nm = 1,000,000,000 nm. This is a 9-order-of-magnitude conversion from nano to base.",
    },
  },

  // --- SIGNIFICANT FIGURES: +4 questions (18 → 22) ---
  {
    id: "sigfig-019",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 8370.00?",
      answer_type: "numeric",
      correct_answer: 6,
      explanation: "6 sig figs. Rule 1 (non-zero: 8,3,7), Rule 2 (captive zero: the 0 after 7 is captive because zeros after decimal are significant), Rule 4 (trailing zeros after decimal: 0,0). All 6 digits are significant.",
    },
  },
  {
    id: "sigfig-020",
    topic: "significant-figures",
    subtopic: "counting",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 0.090?",
      answer_type: "numeric",
      correct_answer: 2,
      explanation: "2 sig figs. The leading zeros (0.0) are insignificant (Rule 3). The 9 is significant (Rule 1). The trailing zero after the decimal is significant (Rule 4). Total: 9 and 0 = 2 sig figs.",
    },
  },
  {
    id: "sigfig-021",
    topic: "significant-figures",
    subtopic: "scientific-notation",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "How many significant figures are in 4.900 × 10⁵?",
      answer_type: "numeric",
      correct_answer: 4,
      explanation: "4 sig figs. In scientific notation, all digits in the mantissa (4.900) are significant. The trailing zeros after the decimal are significant (Rule 4). The exponent doesn't affect sig figs.",
    },
  },
  {
    id: "sigfig-022",
    topic: "significant-figures",
    subtopic: "defined-conversions",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "How many significant figures does the conversion '1 inch = 2.54 cm' have?",
      answer_type: "multiple-choice",
      correct_answer: "Infinite (it is a defined, exact quantity)",
      choices: [
        "Infinite (it is a defined, exact quantity)",
        "3 sig figs",
        "2 sig figs",
        "1 sig fig",
      ],
      explanation: "The inch-to-cm conversion is a defined quantity (1 inch ≡ 2.54 cm exactly). Defined conversions have infinite significant figures — they never limit the precision of a calculation.",
    },
  },

  // --- DIMENSIONAL ANALYSIS: +8 questions (14 → 22) ---
  {
    id: "diman-015",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Jennifer drives 30 minutes at 70 miles per hour. How many miles does she travel?",
      given: [{ value: 30, unit: "min", sigfigs: 2 }],
      target_unit: "mi",
      solution_chain: [
        { numerator: "1 hr", denominator: "60 min", numerator_value: 1, denominator_value: 60 },
        { numerator: "70 mi", denominator: "1 hr", numerator_value: 70, denominator_value: 1 },
      ],
      final_answer: { value: 35, unit: "mi", sigfigs: 2, tolerance_pct: 1 },
      explanation: "30 min × (1 hr / 60 min) × (70 mi / 1 hr) = 35 miles. Two-step: minutes→hours→miles. 2 sig figs (limited by 30 and 70).",
    },
  },
  {
    id: "diman-016",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Mark drives 1 hour at 1.2 km per minute. How many miles does he travel? (1.609 km = 1.000 mile)",
      given: [{ value: 1, unit: "hr", sigfigs: 2 }],
      target_unit: "mi",
      solution_chain: [
        { numerator: "60 min", denominator: "1 hr", numerator_value: 60, denominator_value: 1 },
        { numerator: "1.2 km", denominator: "1 min", numerator_value: 1.2, denominator_value: 1 },
        { numerator: "1 mi", denominator: "1.609 km", numerator_value: 1, denominator_value: 1.609 },
      ],
      final_answer: { value: 45, unit: "mi", sigfigs: 2, tolerance_pct: 2 },
      explanation: "1 hr × (60 min / 1 hr) × (1.2 km / 1 min) × (1 mi / 1.609 km) = 45 miles. Three-step: hr→min→km→mi. 2 sig figs (limited by 1.2).",
    },
  },
  {
    id: "diman-017",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "An oak tree has 2.0 × 10⁵ leaves, each with mass 5.0 g. What is the total leaf mass in pounds? (1.00 pound = 453.6 g)",
      given: [{ value: 200000, unit: "leaves", sigfigs: 2 }],
      target_unit: "lb",
      solution_chain: [
        { numerator: "5.0 g", denominator: "1 leaf", numerator_value: 5.0, denominator_value: 1 },
        { numerator: "1 lb", denominator: "453.6 g", numerator_value: 1, denominator_value: 453.6 },
      ],
      final_answer: { value: 2200, unit: "lb", sigfigs: 2, tolerance_pct: 2 },
      explanation: "2.0 × 10⁵ leaves × (5.0 g / leaf) × (1 lb / 453.6 g) = 2200 pounds (> 1 ton!). 2 sig figs (limited by 2.0 × 10⁵ and 5.0).",
    },
  },
  {
    id: "diman-018",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Walking burns 100 Calories per mile. If you walk 3.5 mph, how many hours to burn 3000 Calories?",
      given: [{ value: 3000, unit: "Cal", sigfigs: 4 }],
      target_unit: "hr",
      solution_chain: [
        { numerator: "1 mi", denominator: "100 Cal", numerator_value: 1, denominator_value: 100 },
        { numerator: "1 hr", denominator: "3.5 mi", numerator_value: 1, denominator_value: 3.5 },
      ],
      final_answer: { value: 8.6, unit: "hr", sigfigs: 2, tolerance_pct: 2 },
      explanation: "3000 Cal × (1 mi / 100 Cal) × (1 hr / 3.5 mi) = 8.6 hours. 2 sig figs (limited by 3.5). That's a long walk after Thanksgiving!",
    },
  },
  {
    id: "diman-019",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Ocean water has 35,000 ppm salt (mg/L). How many gallons produce 26.0 oz of sea salt? (1.00 g = 0.03527 oz; 1.00 gallon = 3.78 L)",
      given: [{ value: 26.0, unit: "oz", sigfigs: 3 }],
      target_unit: "gal",
      solution_chain: [
        { numerator: "1 g", denominator: "0.03527 oz", numerator_value: 1, denominator_value: 0.03527 },
        { numerator: "1000 mg", denominator: "1 g", numerator_value: 1000, denominator_value: 1 },
        { numerator: "1 L", denominator: "35000 mg", numerator_value: 1, denominator_value: 35000 },
        { numerator: "1 gal", denominator: "3.78 L", numerator_value: 1, denominator_value: 3.78 },
      ],
      final_answer: { value: 5.57, unit: "gal", sigfigs: 3, tolerance_pct: 2 },
      explanation: "26.0 oz × (1 g / 0.03527 oz) × (1000 mg / 1 g) × (1 L / 35000 mg) × (1 gal / 3.78 L) = 5.57 gallons. Four-step conversion. 3 sig figs.",
    },
  },
  {
    id: "diman-020",
    topic: "dimensional-analysis",
    subtopic: "concept",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "40 mi/hr is equivalent to 1 hr/40 mi. But 40 ≠ 0.025 (1/40). Explain this apparent discrepancy.",
      answer_type: "multiple-choice",
      correct_answer: "The units make them equivalent — 40 mi/hr and 1/40 hr/mi describe the same rate",
      choices: [
        "The units make them equivalent — 40 mi/hr and 1/40 hr/mi describe the same rate",
        "This is a mathematical error",
        "They are not actually equivalent",
        "The conversion only works for whole numbers",
      ],
      explanation: "40 mi/hr means 40 miles per hour. 1 hr/40 mi means 1 hour per 40 miles — the same rate expressed as a reciprocal. The numbers are different (40 vs 0.025) but the units make them equivalent. Units matter!",
    },
  },
  {
    id: "diman-021",
    topic: "dimensional-analysis",
    subtopic: "equivalent-expressions",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which expressions are equivalent to 40 mi/hr? (Select all that apply conceptually)",
      answer_type: "multiple-choice",
      correct_answer: "40 mi/1 hr, 1 hr/40 mi, and 1 hr = 40 mi",
      choices: [
        "40 mi/1 hr only",
        "40 mi/1 hr, 1 hr/40 mi, and 1 hr = 40 mi",
        "1/40 hr/mi only",
        "40 mi × 1 hr",
      ],
      explanation: "All three forms are equivalent: 40 mi/1 hr (direct), 1 hr/40 mi (reciprocal), and 1 hr = 40 mi (equality). They all describe the same rate. The key insight is that conversion factors can be written either way.",
    },
  },
  {
    id: "diman-022",
    topic: "dimensional-analysis",
    subtopic: "multi-step",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Ben walks 10 steps = 7.25 m, at 1.50 steps/s. How many minutes to walk 2.00 miles? (1.609 km = 1.000 mile)",
      given: [{ value: 2.00, unit: "mi", sigfigs: 3 }],
      target_unit: "min",
      solution_chain: [
        { numerator: "1.609 km", denominator: "1 mi", numerator_value: 1.609, denominator_value: 1 },
        { numerator: "1000 m", denominator: "1 km", numerator_value: 1000, denominator_value: 1 },
        { numerator: "10 steps", denominator: "7.25 m", numerator_value: 10, denominator_value: 7.25 },
        { numerator: "1 s", denominator: "1.50 steps", numerator_value: 1, denominator_value: 1.5 },
        { numerator: "1 min", denominator: "60 s", numerator_value: 1, denominator_value: 60 },
      ],
      final_answer: { value: 49.3, unit: "min", sigfigs: 3, tolerance_pct: 2 },
      explanation: "2.00 mi × (1.609 km / 1 mi) × (1000 m / 1 km) × (10 steps / 7.25 m) × (1 s / 1.50 steps) × (1 min / 60 s) = 49.3 min. Five-step conversion! 3 sig figs.",
    },
  },

  // --- THE MOLE: +6 questions (14 → 20) ---
  {
    id: "mole-015",
    topic: "the-mole",
    subtopic: "mole-concept",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "A mole is similar to which of the following?",
      answer_type: "multiple-choice",
      correct_answer: "A dozen",
      choices: ["A dozen", "A gallon", "A meter", "A degree"],
      explanation: "A mole is a counting number, just like a dozen = 12. A mole = 6.02 × 10²³. Both are quantities that count particles/objects.",
    },
  },
  {
    id: "mole-016",
    topic: "the-mole",
    subtopic: "isotopes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "What are isotopes?",
      answer_type: "multiple-choice",
      correct_answer: "Atoms of the same element with different numbers of neutrons",
      choices: [
        "Atoms of the same element with different numbers of neutrons",
        "Atoms of different elements with the same mass",
        "Atoms with different numbers of protons",
        "Charged atoms with extra electrons",
      ],
      explanation: "Isotopes are atoms of the same element (same # of protons) but different numbers of neutrons, giving them different masses. Example: Carbon-12, Carbon-13, Carbon-14 all have 6 protons but 6, 7, or 8 neutrons.",
    },
  },
  {
    id: "mole-017",
    topic: "the-mole",
    subtopic: "isotopes",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Do the masses on the periodic table correspond to a specific isotope?",
      answer_type: "multiple-choice",
      correct_answer: "No — they are a weighted average of all naturally occurring isotopes",
      choices: [
        "No — they are a weighted average of all naturally occurring isotopes",
        "Yes — they show the most common isotope",
        "Yes — they show the most stable isotope",
        "No — they are randomly chosen",
      ],
      explanation: "Periodic table masses are weighted averages based on natural abundance. For example, Cl has mass 35.45 because it's a mix of Cl-35 (75.8%) and Cl-37 (24.2%). A different planet might have different isotope abundances and thus different average masses.",
    },
  },
  {
    id: "mole-018",
    topic: "the-mole",
    subtopic: "mmol-calculations",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Which has more sodium ions: 120 mmol NaCl or 75 mmol Na₂SO₄? How many mmol Na⁺ does the larger one have?",
      given: [{ value: 75, unit: "mmol Na₂SO₄", sigfigs: 2 }],
      target_unit: "mmol Na⁺",
      solution_chain: [
        { numerator: "2 mmol Na⁺", denominator: "1 mmol Na₂SO₄", numerator_value: 2, denominator_value: 1 },
      ],
      final_answer: { value: 150, unit: "mmol Na⁺", sigfigs: 2, tolerance_pct: 1 },
      explanation: "Na₂SO₄ has 2 Na⁺ per formula unit. 75 mmol Na₂SO₄ × (2 mmol Na⁺ / 1 mmol Na₂SO₄) = 150 mmol Na⁺. Compare to 120 mmol NaCl × 1 = 120 mmol Na⁺. Na₂SO₄ has MORE Na⁺ (150 > 120).",
    },
  },
  {
    id: "mole-019",
    topic: "the-mole",
    subtopic: "mmol-calculations",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Which has more Na⁺: 0.45 mmol NaNO₃ or 750 mL of 450 µM NaNO₃? How many mmol Na⁺ does the larger one have?",
      given: [{ value: 0.45, unit: "mmol NaNO₃", sigfigs: 2 }],
      target_unit: "mmol Na⁺",
      solution_chain: [
        { numerator: "1 mmol Na⁺", denominator: "1 mmol NaNO₃", numerator_value: 1, denominator_value: 1 },
      ],
      final_answer: { value: 0.45, unit: "mmol Na⁺", sigfigs: 2, tolerance_pct: 1 },
      explanation: "0.45 mmol NaNO₃ × (1 mmol Na⁺ / 1 mmol NaNO₃) = 0.45 mmol Na⁺. For the solution: 750 mL × (1 L/1000 mL) × (450 µmol/L) × (1 mmol/1000 µmol) = 0.34 mmol Na⁺. So 0.45 mmol NaNO₃ has MORE Na⁺ (0.45 > 0.34).",
    },
  },
  {
    id: "mole-020",
    topic: "the-mole",
    subtopic: "isotope-table",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "An isotope has 30 protons, 34 neutrons, and 28 electrons. What is its charge?",
      answer_type: "multiple-choice",
      correct_answer: "2+",
      choices: ["2+", "2−", "Neutral", "4+"],
      explanation: "Protons = 30 (positive charge +30). Electrons = 28 (negative charge −28). Net charge = +30 − 28 = +2, so the ion is 2+. This is Zn²⁺ (zinc ion, mass number 64).",
    },
  },

  // --- STOICHIOMETRY: +6 questions (14 → 20) ---
  {
    id: "stoic-015",
    topic: "stoichiometry",
    subtopic: "balancing-equations",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Balance: C₁₈H₃₄O₂ + O₂ → CO₂ + H₂O. What is the coefficient of O₂?",
      answer_type: "numeric",
      correct_answer: 51,
      explanation: "2 C₁₈H₃₄O₂ + 51 O₂ → 36 CO₂ + 34 H₂O. Carbon: 2×18=36. Hydrogen: 2×34=68→34×2=68. Oxygen: 2×2 + 51×2 = 4+102=106 on left; 36×2 + 34×1 = 72+34=106 on right. Balanced!",
    },
  },
  {
    id: "stoic-016",
    topic: "stoichiometry",
    subtopic: "balancing-equations",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "Balance: CaCl₂ + H₃PO₄ → Ca₃(PO₄)₂ + HCl. What is the coefficient of HCl?",
      answer_type: "numeric",
      correct_answer: 6,
      explanation: "3 CaCl₂ + 2 H₃PO₄ → 1 Ca₃(PO₄)₂ + 6 HCl. Ca: 3→3. Cl: 6→6. H: 6→6. PO₄: 2→2. Balanced! The coefficient of HCl is 6.",
    },
  },
  {
    id: "stoic-017",
    topic: "stoichiometry",
    subtopic: "balancing-equations",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Balance: FeS₂ + O₂ → Fe₂O₃ + SO₂. What is the coefficient of O₂?",
      answer_type: "numeric",
      correct_answer: 11,
      explanation: "4 FeS₂ + 11 O₂ → 2 Fe₂O₃ + 8 SO₂. Fe: 4→4. S: 8→8. O: 22→6+16=22. Balanced! The coefficient of O₂ is 11.",
    },
  },
  {
    id: "stoic-018",
    topic: "stoichiometry",
    subtopic: "mass-to-mass",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "Oleic acid (C₁₈H₃₄O₂, MM = 282 g/mol) burns: 2C₁₈H₃₄O₂ + 51O₂ → 36CO₂ + 34H₂O. How many grams of CO₂ from 1.00 g oleic acid?",
      given: [{ value: 1.00, unit: "g C₁₈H₃₄O₂", sigfigs: 3 }],
      target_unit: "g CO₂",
      solution_chain: [
        { numerator: "1 mol C₁₈H₃₄O₂", denominator: "282 g C₁₈H₃₄O₂", numerator_value: 1, denominator_value: 282 },
        { numerator: "36 mol CO₂", denominator: "2 mol C₁₈H₃₄O₂", numerator_value: 36, denominator_value: 2 },
        { numerator: "44 g CO₂", denominator: "1 mol CO₂", numerator_value: 44, denominator_value: 1 },
      ],
      final_answer: { value: 2.81, unit: "g CO₂", sigfigs: 3, tolerance_pct: 2 },
      explanation: "1.00 g × (1 mol / 282 g) × (36 mol CO₂ / 2 mol C₁₈H₃₄O₂) × (44 g / 1 mol) = 2.81 g CO₂. Three-step: g→mol→mol→g. 3 sig figs.",
    },
  },
  {
    id: "stoic-019",
    topic: "stoichiometry",
    subtopic: "limiting-reactant",
    mode: "quiz",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "For 3CaCl₂ + 2H₃PO₄ → Ca₃(PO₄)₂ + 6HCl: If you react 20.0 g CaCl₂ with 20.0 g H₃PO₄, which is limiting? (MM CaCl₂ = 111 g/mol, H₃PO₄ = 98.0 g/mol)",
      answer_type: "multiple-choice",
      correct_answer: "CaCl₂ is limiting",
      choices: [
        "CaCl₂ is limiting",
        "H₃PO₄ is limiting",
        "Both are limiting",
        "Neither is limiting",
      ],
      explanation: "20.0 g CaCl₂ ÷ 111 g/mol = 0.180 mol CaCl₂ → can make 0.0601 mol product. 20.0 g H₃PO₄ ÷ 98.0 g/mol = 0.204 mol H₃PO₄ → can make 0.102 mol product. CaCl₂ makes less product, so it's limiting. You'd make 18.6 g Ca₃(PO₄)₂.",
    },
  },
  {
    id: "stoic-020",
    topic: "stoichiometry",
    subtopic: "gas-volume",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "4FeS₂ + 11O₂ → 2Fe₂O₃ + 8SO₂. How many liters of O₂ (1.00 mol gas = 22.4 L) react with 5.00 g FeS₂? (MM FeS₂ = 120 g/mol)",
      given: [{ value: 5.00, unit: "g FeS₂", sigfigs: 3 }],
      target_unit: "L O₂",
      solution_chain: [
        { numerator: "1 mol FeS₂", denominator: "120 g FeS₂", numerator_value: 1, denominator_value: 120 },
        { numerator: "11 mol O₂", denominator: "4 mol FeS₂", numerator_value: 11, denominator_value: 4 },
        { numerator: "22.4 L O₂", denominator: "1 mol O₂", numerator_value: 22.4, denominator_value: 1 },
      ],
      final_answer: { value: 2.57, unit: "L O₂", sigfigs: 3, tolerance_pct: 2 },
      explanation: "5.00 g × (1 mol / 120 g) × (11 mol O₂ / 4 mol FeS₂) × (22.4 L / 1 mol) = 2.57 L O₂. Three-step: g→mol→mol→L. 3 sig figs.",
    },
  },

  // --- MOLARITY & DILUTIONS: +6 questions (14 → 20) ---
  {
    id: "molarity-015",
    topic: "molarity-dilutions",
    subtopic: "stock-solutions",
    mode: "quiz",
    difficulty: 1,
    is_sample: true,
    content: {
      prompt: "Why do we make stock solutions in labs instead of making the desired concentration directly?",
      answer_type: "multiple-choice",
      correct_answer: "Both: faster to dilute, and avoids weighing very small masses",
      choices: [
        "Both: faster to dilute, and avoids weighing very small masses",
        "Stock solutions are more accurate",
        "It's required by safety regulations",
        "Stock solutions never expire",
      ],
      explanation: "Two main reasons: (1) It's faster to measure a volume of stock than to weigh and dissolve solid each time. (2) For dilute solutions, the mass needed may be too small to weigh accurately (e.g., 0.100 mg is harder to measure than 1.0 g).",
    },
  },
  {
    id: "molarity-016",
    topic: "molarity-dilutions",
    subtopic: "serial-dilution",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A 500 mM solution is diluted 1:10, then the result is diluted 1:10 again. What is the final concentration?",
      answer_type: "numeric",
      correct_answer: 5,
      explanation: "First dilution: 500/10 = 50 mM. Second dilution: 50/10 = 5 mM. Total dilution factor = 10 × 10 = 100. Final = 500/100 = 5.00 mM.",
    },
  },
  {
    id: "molarity-017",
    topic: "molarity-dilutions",
    subtopic: "serial-dilution",
    mode: "quiz",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "A solution is diluted 1:100, then 1:10. The final concentration is 15 mg/mL. What was the original concentration?",
      answer_type: "numeric",
      correct_answer: 15000,
      explanation: "Total dilution factor = 100 × 10 = 1000. Original = 15 × 1000 = 15,000 mg/mL. Serial dilutions multiply: each dilution factor compounds.",
    },
  },
  {
    id: "molarity-018",
    topic: "molarity-dilutions",
    subtopic: "dilution-calculation",
    mode: "solver",
    difficulty: 2,
    is_sample: true,
    content: {
      prompt: "5.00 mL of 15.0 M stock is diluted to 100 mL. What is the final concentration?",
      given: [{ value: 5.00, unit: "mL", sigfigs: 3 }],
      target_unit: "M",
      solution_chain: [
        { numerator: "15.0 M", denominator: "1", numerator_value: 15.0, denominator_value: 1 },
        { numerator: "5.00 mL", denominator: "100 mL", numerator_value: 5.0, denominator_value: 100 },
      ],
      final_answer: { value: 0.750, unit: "M", sigfigs: 3, tolerance_pct: 1 },
      explanation: "C₁V₁ = C₂V₂ → C₂ = (15.0 M × 5.00 mL) / 100 mL = 0.750 M. 3 sig figs. Remember: you take 5 mL of stock and add solvent to reach 100 mL total (not add 95 mL water).",
    },
  },
  {
    id: "molarity-019",
    topic: "molarity-dilutions",
    subtopic: "dilution-calculation",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "A 0.0500 L aliquot of stock is diluted to 1.30 L. Final concentration = 42.0 mM. What was the stock concentration?",
      given: [{ value: 42.0, unit: "mM", sigfigs: 3 }],
      target_unit: "mM",
      solution_chain: [
        { numerator: "1.30 L", denominator: "0.0500 L", numerator_value: 1.3, denominator_value: 0.05 },
      ],
      final_answer: { value: 1090, unit: "mM", sigfigs: 3, tolerance_pct: 2 },
      explanation: "C₁V₁ = C₂V₂ → C₁ = (42.0 mM × 1.30 L) / 0.0500 L = 1090 mM = 1.09 × 10³ mM. 3 sig figs. The stock is ~26× more concentrated than the dilute solution.",
    },
  },
  {
    id: "molarity-020",
    topic: "molarity-dilutions",
    subtopic: "dilution-calculation",
    mode: "solver",
    difficulty: 3,
    is_sample: true,
    content: {
      prompt: "You have 125 mg/mL stock. You need 500 mL of 65.0 µg/mL. How many mL of stock do you need?",
      given: [{ value: 500, unit: "mL", sigfigs: 3 }],
      target_unit: "mL",
      solution_chain: [
        { numerator: "65.0 µg", denominator: "1 mL", numerator_value: 65.0, denominator_value: 1 },
        { numerator: "1 mL", denominator: "125000 µg", numerator_value: 1, denominator_value: 125000 },
      ],
      final_answer: { value: 0.260, unit: "mL", sigfigs: 3, tolerance_pct: 2 },
      explanation: "C₁V₁ = C₂V₂. First convert: 125 mg/mL = 125,000 µg/mL. V₁ = (65.0 µg/mL × 500 mL) / 125,000 µg/mL = 0.260 mL. Take 0.260 mL of stock and dilute to 500 mL total. 3 sig figs.",
    },
  },
];
